/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as ConnectedSystemsRouteImport } from './routes/connected-systems'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as LogisticsRouteImport } from './routes/logistics'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as TrackShipmentRouteImport } from './routes/track-shipment'
import { Route as WhyPriorityRouteImport } from './routes/why-priority'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const ConnectedSystemsRoute = ConnectedSystemsRouteImport.update({
  id: '/connected-systems',
  path: '/connected-systems',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const LogisticsRoute = LogisticsRouteImport.update({
  id: '/logistics',
  path: '/logistics',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const TrackShipmentRoute = TrackShipmentRouteImport.update({
  id: '/track-shipment',
  path: '/track-shipment',
  getParentRoute: () => rootRouteImport,
} as any)
const WhyPriorityRoute = WhyPriorityRouteImport.update({
  id: '/why-priority',
  path: '/why-priority',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/connected-systems': typeof ConnectedSystemsRoute
  '/contact': typeof ContactRoute
  '/logistics': typeof LogisticsRoute
  '/services': typeof ServicesRoute
  '/track-shipment': typeof TrackShipmentRoute
  '/why-priority': typeof WhyPriorityRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/connected-systems': typeof ConnectedSystemsRoute
  '/contact': typeof ContactRoute
  '/logistics': typeof LogisticsRoute
  '/services': typeof ServicesRoute
  '/track-shipment': typeof TrackShipmentRoute
  '/why-priority': typeof WhyPriorityRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/connected-systems': typeof ConnectedSystemsRoute
  '/contact': typeof ContactRoute
  '/logistics': typeof LogisticsRoute
  '/services': typeof ServicesRoute
  '/track-shipment': typeof TrackShipmentRoute
  '/why-priority': typeof WhyPriorityRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/connected-systems'
    | '/contact'
    | '/logistics'
    | '/services'
    | '/track-shipment'
    | '/why-priority'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/connected-systems'
    | '/contact'
    | '/logistics'
    | '/services'
    | '/track-shipment'
    | '/why-priority'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/connected-systems'
    | '/contact'
    | '/logistics'
    | '/services'
    | '/track-shipment'
    | '/why-priority'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ConnectedSystemsRoute: typeof ConnectedSystemsRoute
  ContactRoute: typeof ContactRoute
  LogisticsRoute: typeof LogisticsRoute
  ServicesRoute: typeof ServicesRoute
  TrackShipmentRoute: typeof TrackShipmentRoute
  WhyPriorityRoute: typeof WhyPriorityRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/connected-systems': {
      id: '/connected-systems'
      path: '/connected-systems'
      fullPath: '/connected-systems'
      preLoaderRoute: typeof ConnectedSystemsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logistics': {
      id: '/logistics'
      path: '/logistics'
      fullPath: '/logistics'
      preLoaderRoute: typeof LogisticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/track-shipment': {
      id: '/track-shipment'
      path: '/track-shipment'
      fullPath: '/track-shipment'
      preLoaderRoute: typeof TrackShipmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/why-priority': {
      id: '/why-priority'
      path: '/why-priority'
      fullPath: '/why-priority'
      preLoaderRoute: typeof WhyPriorityRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ConnectedSystemsRoute: ConnectedSystemsRoute,
  ContactRoute: ContactRoute,
  LogisticsRoute: LogisticsRoute,
  ServicesRoute: ServicesRoute,
  TrackShipmentRoute: TrackShipmentRoute,
  WhyPriorityRoute: WhyPriorityRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
